### ISSUE TITLE
Notifications Permission in Dose Deck/NewMed.swift

### ISSUE THREAD

**Issue by vignesh1507** [TartejBrothers/Dose-Deck#25]
Notifications Permission: Before scheduling notifications, ensure that permission to send notifications is requested from the user. Without requesting permission, the notification will not be delivered. You can do this in your `dispatchNotification` function:

```bash
UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .sound, .badge]) { granted, error in
    if granted {
        // Proceed with scheduling the notification
    } else {
        print("Permission denied.")
    }
}
```

**Comment by TartejBrothers** [comment]
This code snippet is already present in the contentview, and is called when the app first lauches
