### ISSUE TITLE
Alignment Issues in SecureField: Dose Deck/ContentView.swift

### ISSUE THREAD

**Issue by vignesh1507** [TartejBrothers/Dose-Deck#26]
The `Text` elements for labels like "Enter Your Email" or "Enter Your Password" are offset with hardcoded values (`offset(x: -100)`). This is prone to layout issues across different device sizes. You might want to use `.frame(maxWidth: .infinity, alignment: .leading)` for better alignment control.

**Comment by TartejBrothers** [comment]
As far I remember, testing it on different phone screen sizes, it was not a problem and this just limited to iPhone so it should not be a problem.
